/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'codeSnippet' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLesson' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Difficulty],
      [IDL.Nat],
      [],
    ),
  'getLessonById' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'listAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'markComplete' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'codeSnippet' : IDL.Text,
  });
  
  return IDL.Service({
    'addLesson' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Difficulty],
        [IDL.Nat],
        [],
      ),
    'getLessonById' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'listAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'markComplete' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };