/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'difficulty' : Difficulty,
  'description' : string,
  'codeSnippet' : string,
}
export interface _SERVICE {
  'addLesson' : ActorMethod<[string, string, string, Difficulty], bigint>,
  'getLessonById' : ActorMethod<[bigint], [] | [Lesson]>,
  'getProgress' : ActorMethod<[], Array<bigint>>,
  'listAllLessons' : ActorMethod<[], Array<Lesson>>,
  'markComplete' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];